export const courseLinks = {
    // Graduate CS courses
    "Applied Machine Learning": "https://kuleshov-group.github.io/aml-website/",
    "Machine Learning Engineering": "https://classes.cornell.edu/browse/roster/FA24/class/CS/5781",
    "Advanced Algorithms": "https://classes.cornell.edu/browse/roster/FA24/class/CS/5112",
    "HCI and Design": "https://classes.cornell.edu/browse/roster/FA24/class/CS/5682",
    "Product Development Studio": "https://tech.cornell.edu/studio/curriculum/product-studio/",
    "Startup Studio": "https://tech.cornell.edu/studio/curriculum/startup-studio/",
    "Venture Capital": "https://classes.cornell.edu/browse/roster/SP25/class/TECH/5130",
    "Full Stack Development": "https://classes.cornell.edu/browse/roster/SP25/class/CS/5356",
    "Data Engineering": "https://classes.cornell.edu/browse/roster/SP25/class/CS/5304",
    "Machine Learning Hardware": "https://abdelfattah-class.github.io/ece5545/",
    "Security and Privacy": "https://classes.cornell.edu/browse/roster/SP25/class/TECH/5270",

    // Undergraduate CS courses
    "Data Structures": "https://www.vanderbilt.edu/catalogs/kuali/undergraduate-24-25.php#/courses/Hy3itpn2O?group=Computer%20Science&bc=true&bcCurrent=Computer%20Science&bcItemType=courses&bc=true&bcCurrent=CS2201%20-%20Program%20Design%20and%20Data%20Structures&bcGroup=Computer%20Science&bcItemType=courses",
    "Algorithms": "https://www.vanderbilt.edu/catalogs/kuali/undergraduate-24-25.php#/courses/r1LBSvTn3u?bc=true&bcCurrent=CS3250%20-%20Algorithms&bcGroup=Computer%20Science&bcItemType=courses",
    "Software Engineering": "https://huang.isis.vanderbilt.edu/cs4278/",
    "Database Systems": "https://www.vanderbilt.edu/catalogs/kuali/undergraduate-24-25.php#/courses/rk73oFannO?bc=true&bcCurrent=CS3265%20-%20Database%20Management%20Systems&bcGroup=Computer%20Science&bcItemType=courses",
    "Operating Systems": "https://www.vanderbilt.edu/catalogs/kuali/undergraduate-24-25.php#/courses/BkdBvTh3u?group=Computer%20Science&bc=true&bcCurrent=Computer%20Science&bcItemType=courses&bc=true&bcCurrent=CS3281%20-%20Principles%20of%20Operating%20Systems%20I&bcGroup=Computer%20Science&bcItemType=courses",
    "Java Programming": "https://www.vanderbilt.edu/catalogs/kuali/undergraduate-24-25.php#/courses/r1LHv6hnO?group=Computer%20Science&bc=true&bcCurrent=Computer%20Science&bcItemType=courses&bc=true&bcCurrent=CS1101%20-%20Programming%20and%20Problem%20Solving&bcGroup=Computer%20Science&bcItemType=courses",
    "Discrete Math": "https://www.vanderbilt.edu/catalogs/kuali/undergraduate-24-25.php#/courses/SkvSvT3h_?group=Computer%20Science&bc=true&bcCurrent=Computer%20Science&bcItemType=courses&bc=true&bcCurrent=CS2212%20-%20Discrete%20Structures&bcGroup=Computer%20Science&bcItemType=courses",
    "Software Design": "https://www.vanderbilt.edu/catalogs/kuali/undergraduate-24-25.php#/courses/BJVHrw6hhO?group=Computer%20Science&bc=true&bcCurrent=Computer%20Science&bcItemType=courses&bc=true&bcCurrent=CS3251%20-%20Intermediate%20Software%20Design&bcGroup=Computer%20Science&bcItemType=courses",
    "Computers & Ethics": "https://www.vanderbilt.edu/catalogs/kuali/undergraduate-24-25.php#/courses/SyNHSPT33O?group=Computer%20Science&bc=true&bcCurrent=Computer%20Science&bcItemType=courses&bc=true&bcCurrent=CS1151%20-%20Computers%20and%20Ethics&bcGroup=Computer%20Science&bcItemType=courses",
    "Computer Architecture": "https://www.vanderbilt.edu/catalogs/kuali/undergraduate-24-25.php#/courses/r1P5WmY1n?group=Computer%20Science&bc=true&bcCurrent=Computer%20Science&bcItemType=courses&bc=true&bcCurrent=CS2123%20-%20Digital%20Systems&bcGroup=Computer%20Science&bcItemType=courses",
    "Programming Languages": "https://www.vanderbilt.edu/catalogs/kuali/undergraduate-24-25.php#/courses/rylR4Kp2nu?group=Computer%20Science&bc=true&bcCurrent=Computer%20Science&bcItemType=courses&bc=true&bcCurrent=CS3270%20-%20Programming%20Languages&bcGroup=Computer%20Science&bcItemType=courses",
    "Independent Research": "https://smarttransit.ai/",
    "Network Analysis": "https://www.vanderbilt.edu/catalogs/kuali/undergraduate-24-25.php#/courses/S13qeK5Pc?group=Computer%20Science&bc=true&bcCurrent=Computer%20Science&bcItemType=courses&bc=true&bcCurrent=CS4352%20-%20Social%20Network%20Analysis&bcGroup=Computer%20Science&bcItemType=courses",
    "Virtual Reality Design": "https://www.vanderbilt.edu/catalogs/kuali/undergraduate-24-25.php#/courses/rkeJyta22d?group=Computer%20Science&bc=true&bcCurrent=Computer%20Science&bcItemType=courses&bc=true&bcCurrent=CS4249%20-%20Projects%20in%20Virtual%20Reality%20Design&bcGroup=Computer%20Science&bcItemType=courses",
    
    // Human & Organizational Development courses
    "Applied Human Development": "https://www.vanderbilt.edu/catalogs/kuali/undergraduate-24-25.php#/courses/BkWl-dp22d?bc=true&bcCurrent=HOD1250%20-%20Applied%20Human%20Development&bcGroup=Human%20%26%20Organizational%20Development&bcItemType=courses",
    "Leadership Theory": "https://www.vanderbilt.edu/catalogs/kuali/undergraduate-24-25.php#/courses/Hkl6-dp23u?bc=true&bcCurrent=HODL3204%20-%20Leadership%20Theory%20and%20Practice&bcGroup=H%26OD%3A%20Leadership%20%26%20Organizational%20Effectiveness&bcItemType=courses",
    "Systems Thinking": "https://www.vanderbilt.edu/catalogs/kuali/undergraduate-24-25.php#/courses/SkNxZO622d?bc=true&bcCurrent=HOD4951%20-%20Critical%20Reflexivity%20and%20Systems%20Thinking&bcGroup=Human%20%26%20Organizational%20Development&bcItemType=courses",
    "Understanding Organizations": "https://www.vanderbilt.edu/catalogs/kuali/undergraduate-24-25.php#/courses/Hy7V2F63hd?bc=true&bcCurrent=HOD2100%20-%20Understanding%20Organizations&bcGroup=Human%20%26%20Organizational%20Development&bcItemType=courses",
    "Talent Management": "https://www.vanderbilt.edu/catalogs/kuali/undergraduate-24-25.php#/courses/Skf7Zd6nhd?bc=true&bcCurrent=HOD2400%20-%20Talent%20Management%20and%20Organizational%20Fit&bcGroup=Human%20%26%20Organizational%20Development&bcItemType=courses",
    "Systematic Inquiry": "https://www.vanderbilt.edu/catalogs/kuali/undergraduate-24-25.php#/courses/B17xWupn2u?bc=true&bcCurrent=HOD2500%20-%20Systematic%20Inquiry&bcGroup=Human%20%26%20Organizational%20Development&bcItemType=courses",
    "Public Policy": "https://www.vanderbilt.edu/catalogs/kuali/undergraduate-24-25.php#/courses/Bkz_ZdTn2d?bc=true&bcCurrent=HOD2700%20-%20Public%20Policy&bcGroup=Human%20%26%20Organizational%20Development&bcItemType=courses",
    "Advanced Organizational Theory": "https://www.vanderbilt.edu/catalogs/kuali/undergraduate-24-25.php#/courses/S1V4htT3n_?bc=true&bcCurrent=HODL3234%20-%20Advanced%20Organizational%20Theory&bcGroup=H%26OD%3A%20Leadership%20%26%20Organizational%20Effectiveness&bcItemType=courses",
    "Small Group Behavior": "https://www.vanderbilt.edu/catalogs/kuali/undergraduate-24-25.php#/courses/HkBgYa3nO?bc=true&bcCurrent=HOD1300%20-%20Small%20Group%20Behavior&bcGroup=Human%20%26%20Organizational%20Development&bcItemType=courses",
    "Evidence-based Practice in Organizations": "https://www.vanderbilt.edu/catalogs/kuali/undergraduate-24-25.php#/courses/HJWTbuah2O?bc=true&bcCurrent=HODL3264%20-%20Evidence-based%20Practice%20in%20Organizations&bcGroup=H%26OD%3A%20Leadership%20%26%20Organizational%20Effectiveness&bcItemType=courses",
    "Education & Economic Development": "https://www.vanderbilt.edu/catalogs/kuali/undergraduate-24-25.php#/courses/SJpZup32d?bc=true&bcCurrent=HODI3230%20-%20Education%20and%20Economic%20Development&bcGroup=H%26OD%3A%20International%20Leadership%20and%20Policy&bcItemType=courses",
    "Continuous Improvement in Organizations": "https://www.vanderbilt.edu/catalogs/kuali/undergraduate-24-25.php#/courses/BkCdw7lfp?bc=true&bcCurrent=HOD2600%20-%20Continuous%20Improvement%20in%20Organizations&bcGroup=Human%20%26%20Organizational%20Development&bcItemType=courses",
    "Capstone Internship": "https://hodcapstone.wordpress.com/about/",
}; 